#!/bin/bash
set -euo pipefail

URL="$1"

# Validate PR URL format
if [[ ! "$URL" =~ ^https://github\.com/([^/]+)/([^/]+)/pull/([0-9]+)$ ]]; then
  echo "Error: Invalid PR URL. Expected: https://github.com/{owner}/{repo}/pull/{number}"
  exit 1
fi

OWNER="${BASH_REMATCH[1]}"
REPO="${BASH_REMATCH[2]}"
NUMBER="${BASH_REMATCH[3]}"

SKILLS_DIR="$(cd "$(dirname "$0")" && pwd)"

# Fetch file list from PR to determine which reviewers to load
FILES=$(gh pr view "$URL" --json files --jq '.files[].path' 2>/dev/null || true)

if [ -z "$FILES" ]; then
  echo "Error: Unable to fetch PR files. Check GITHUB_TOKEN and PR URL."
  exit 1
fi

# Dynamically load review criteria based on file types present
CRITERIA=""
REVIEWERS=""

if echo "$FILES" | grep -qE '\.(java|gradle|xml)$'; then
  CRITERIA="${CRITERIA}
$(cat "${SKILLS_DIR}/../yepai-review-java/SKILL.md" 2>/dev/null || true)"
  REVIEWERS="${REVIEWERS:+${REVIEWERS}, }Java/Spring"
fi

if echo "$FILES" | grep -qE '\.(py|pyi)$'; then
  CRITERIA="${CRITERIA}
$(cat "${SKILLS_DIR}/../yepai-review-python/SKILL.md" 2>/dev/null || true)"
  REVIEWERS="${REVIEWERS:+${REVIEWERS}, }Python"
fi

if echo "$FILES" | grep -qE '\.(tsx|jsx|ts)$'; then
  CRITERIA="${CRITERIA}
$(cat "${SKILLS_DIR}/../yepai-review-react/SKILL.md" 2>/dev/null || true)"
  REVIEWERS="${REVIEWERS:+${REVIEWERS}, }React/TypeScript"
fi

if [ -z "$CRITERIA" ]; then
  echo "No reviewable files found in this PR. Supported: Java, Python, React/TypeScript."
  echo "Files in PR:"
  echo "$FILES"
  exit 0
fi

echo "Detected reviewers: ${REVIEWERS}"
echo "Starting Claude Code review..."

claude -p "You are an expert code reviewer for YepAI.

Review the GitHub PR at ${URL}.

## Instructions

1. Run: gh pr view ${URL} --json title,body,files,number,headRefName,baseRefName
2. Run: gh pr diff ${URL}
3. Classify changed files by extension and apply the language-specific review criteria from your system prompt.
4. Format findings as markdown with severity (BLOCKER/MAJOR/MINOR), file path, line number, issue description, and recommendation.
5. Post the review to GitHub by running:
   gh api repos/${OWNER}/${REPO}/pulls/${NUMBER}/reviews --method POST -f body='<review markdown>' -f event='COMMENT'
6. If posting fails, output the full review content directly.

## Output Format

# AI Code Review

**Reviewers applied**: [comma-separated list of language reviewers used]

## Summary

[1-3 sentence high-level assessment]

## Major Issues

| Severity | File | Line | Issue | Recommendation |
|----------|------|------|-------|----------------|

## Minor Issues

- \`file:line\` -- Description. Suggestion.

## Suggested Improvements

- [Optional architectural or design improvements]

---
*Review generated by YepAI Code Review (powered by Claude)*
" \
  --append-system-prompt "${CRITERIA}" \
  --model claude-sonnet-4-6 \
  --allowedTools "Bash(gh *)" \
  --dangerously-skip-permissions \
  --output-format text \
  --max-turns 30 \
  --max-budget-usd 5.00
